name = "StringFigures"
uuid = "e16f4e6c-5f6e-4eb2-b51f-acfd3f8f7294"
authors = ["Alfredo Braunstein"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
